- hosts: appservers
  become: yes
  tasks:
    - name: Pull latest Docker image
      command: docker pull memorieso/java-app:latest

    - name: Stop old container
      command: docker rm -f javaapp
      ignore_errors: yes

    - name: Run new container
      command: docker run -d -p 8080:8080 --name javaapp memorieso/java-app:latest
