- name: Deploy Java App Container
  hosts: appservers
  become: yes

  tasks:

    - name: Install Docker (AL2)
      command: yum install -y docker

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      command: usermod -aG docker ec2-user
      ignore_errors: yes

    - name: Pull Docker image
      command: docker pull memorieso/java-app:latest

    - name: Stop old container
      command: docker rm -f javaapp
      ignore_errors: yes

    - name: Run new container
      command: docker run -d -p 8080:8080 --name javaapp memorieso/java-app:latest

